"""add_fixed_every_working_day_and_start_time

Revision ID: 0f76889c3123
Revises: a4617087b9dd
Create Date: 2026-03-23 12:19:37.277770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f76889c3123'
down_revision: Union[str, Sequence[str], None] = 'a4617087b9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add start_time with a default so existing rows get "09:30"
    op.add_column('tt_sections', sa.Column(
        'start_time', sa.String(), nullable=False, server_default='09:30'
    ))

    # Add fixed_every_working_day with default False
    op.add_column('tt_subjects', sa.Column(
        'fixed_every_working_day', sa.Boolean(), nullable=False, server_default='false'
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tt_subjects', 'fixed_every_working_day')
    op.drop_column('tt_sections', 'start_time')
    # ### end Alembic commands ###
