"""update attendance model

Revision ID: 300b3436de26
Revises: eba4c4857e58
Create Date: 2026-03-13 18:08:43.186124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '300b3436de26'
down_revision: Union[str, Sequence[str], None] = 'eba4c4857e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'attendance',
    sa.Column('working_hours', sa.Float(), nullable=False, server_default='0')
    )
    op.add_column(
    'attendance',
    sa.Column('auto_marked', sa.Boolean(), nullable=False, server_default='false')
    )
    op.alter_column('attendance', 'clock_in_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance', 'clock_in_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('attendance', 'auto_marked')
    op.drop_column('attendance', 'working_hours')
    # ### end Alembic commands ###
