"""add_fixed_every_working_day_and_start_time

Revision ID: 38fc66a37f8d
Revises: 0f76889c3123
Create Date: 2026-03-23 13:04:37.099904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fc66a37f8d'
down_revision: Union[str, Sequence[str], None] = '0f76889c3123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
