"""add timetable tables

Revision ID: a4617087b9dd
Revises: 466153f50ae5
Create Date: 2026-03-22 22:28:05.424968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4617087b9dd'
down_revision: Union[str, Sequence[str], None] = '466153f50ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tt_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tt_rooms_id'), 'tt_rooms', ['id'], unique=False)
    op.create_table('tt_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('total_periods_per_day', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.String(), nullable=False),
    sa.Column('lunch_after_period', sa.Integer(), nullable=False),
    sa.Column('lunch_label', sa.String(), nullable=True),
    sa.Column('thub_reserved_periods', sa.String(), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('lunch_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name', 'academic_year', name='uq_tt_sections_department_name_ay')
    )
    op.create_index(op.f('ix_tt_sections_id'), 'tt_sections', ['id'], unique=False)
    op.create_table('tt_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('weekly_hours_non_thub', sa.Integer(), nullable=True),
    sa.Column('weekly_hours_thub', sa.Integer(), nullable=True),
    sa.Column('is_lab', sa.Boolean(), nullable=False),
    sa.Column('min_continuous_periods', sa.Integer(), nullable=False),
    sa.Column('max_continuous_periods', sa.Integer(), nullable=False),
    sa.Column('requires_room_type', sa.String(), nullable=True),
    sa.Column('default_room_name', sa.String(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('fixed_day', sa.Integer(), nullable=True),
    sa.Column('fixed_days', sa.String(), nullable=True),
    sa.Column('fixed_start_period', sa.Integer(), nullable=True),
    sa.Column('fixed_span', sa.Integer(), nullable=False),
    sa.Column('allowed_days', sa.String(), nullable=True),
    sa.Column('allowed_periods', sa.String(), nullable=True),
    sa.Column('no_faculty_required', sa.Boolean(), nullable=False),
    sa.Column('allow_same_day_repeat', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'year', 'semester', 'academic_year', 'code', name='uq_tt_subjects_department_year_sem_ay_code')
    )
    op.create_index(op.f('ix_tt_subjects_id'), 'tt_subjects', ['id'], unique=False)
    op.create_table('tt_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('is_lab_continuation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['tt_rooms.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['tt_sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['tt_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'day_index', 'period_index', name='uq_tt_entries_section_day_period')
    )
    op.create_index(op.f('ix_tt_entries_id'), 'tt_entries', ['id'], unique=False)
    op.create_table('tt_faculty_subject_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('max_hours_per_day', sa.Integer(), nullable=True),
    sa.Column('can_handle_lab', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['tt_subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'subject_id', name='uq_tt_faculty_subject_map_faculty_subject')
    )
    op.create_index(op.f('ix_tt_faculty_subject_map_id'), 'tt_faculty_subject_map', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tt_faculty_subject_map_id'), table_name='tt_faculty_subject_map')
    op.drop_table('tt_faculty_subject_map')
    op.drop_index(op.f('ix_tt_entries_id'), table_name='tt_entries')
    op.drop_table('tt_entries')
    op.drop_index(op.f('ix_tt_subjects_id'), table_name='tt_subjects')
    op.drop_table('tt_subjects')
    op.drop_index(op.f('ix_tt_sections_id'), table_name='tt_sections')
    op.drop_table('tt_sections')
    op.drop_index(op.f('ix_tt_rooms_id'), table_name='tt_rooms')
    op.drop_table('tt_rooms')
    # ### end Alembic commands ###
