"""add category wise continuous period fields to timetable subjects

Revision ID: bb3cba9ab6a1
Revises: cbaa43792c6e
Create Date: 2026-03-23 22:29:09.861676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3cba9ab6a1'
down_revision: Union[str, Sequence[str], None] = 'cbaa43792c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
