"""add docs module tables

Revision ID: bc39e8d8892f
Revises: 300b3436de26
Create Date: 2026-03-13 23:34:04.650104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39e8d8892f'
down_revision: Union[str, Sequence[str], None] = '300b3436de26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('subjects_code_key'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_code_key'), 'subjects', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'uploaded_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
