"""add applies_to_category to tt_subjects

Revision ID: cbaa43792c6e
Revises: 38fc66a37f8d
Create Date: 2026-03-23 14:31:25.366118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbaa43792c6e'
down_revision: Union[str, Sequence[str], None] = '38fc66a37f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tt_subjects', sa.Column('applies_to_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tt_subjects', 'applies_to_category')
    # ### end Alembic commands ###
